//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newconsoleappdbfirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class studentmark
    {
        public int id { get; set; }
        public string stud_name { get; set; }
        public string sub_name { get; set; }
        public int marks { get; set; }
    }
}
