//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addition", ReplyAction="http://tempuri.org/IService1/additionResponse")]
        int addition(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addition", ReplyAction="http://tempuri.org/IService1/additionResponse")]
        System.Threading.Tasks.Task<int> additionAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/subtraction", ReplyAction="http://tempuri.org/IService1/subtractionResponse")]
        int subtraction(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/subtraction", ReplyAction="http://tempuri.org/IService1/subtractionResponse")]
        System.Threading.Tasks.Task<int> subtractionAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/multiplication", ReplyAction="http://tempuri.org/IService1/multiplicationResponse")]
        int multiplication(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/multiplication", ReplyAction="http://tempuri.org/IService1/multiplicationResponse")]
        System.Threading.Tasks.Task<int> multiplicationAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/division", ReplyAction="http://tempuri.org/IService1/divisionResponse")]
        int division(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/division", ReplyAction="http://tempuri.org/IService1/divisionResponse")]
        System.Threading.Tasks.Task<int> divisionAsync(int a, int b);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WindowsFormsApp1.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WindowsFormsApp1.ServiceReference1.IService1>, WindowsFormsApp1.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int addition(int a, int b) {
            return base.Channel.addition(a, b);
        }
        
        public System.Threading.Tasks.Task<int> additionAsync(int a, int b) {
            return base.Channel.additionAsync(a, b);
        }
        
        public int subtraction(int a, int b) {
            return base.Channel.subtraction(a, b);
        }
        
        public System.Threading.Tasks.Task<int> subtractionAsync(int a, int b) {
            return base.Channel.subtractionAsync(a, b);
        }
        
        public int multiplication(int a, int b) {
            return base.Channel.multiplication(a, b);
        }
        
        public System.Threading.Tasks.Task<int> multiplicationAsync(int a, int b) {
            return base.Channel.multiplicationAsync(a, b);
        }
        
        public int division(int a, int b) {
            return base.Channel.division(a, b);
        }
        
        public System.Threading.Tasks.Task<int> divisionAsync(int a, int b) {
            return base.Channel.divisionAsync(a, b);
        }
    }
}
